// Author: Ratheesh G Kumar — Backend Engineer (Golang)
// Destination: Back-End/neptune-pamm-server/pkg/utilis/jwt.go
// Role: Security — JWT access/refresh tokens
// Description: HS256 JWT manager. Every access token carries a unique jti so logout can deny it
// in Redis until expiry. Parse rejects any alg other than HS256 (alg-confusion defence).

package utilis

import (
	"errors"
	"fmt"
	"time"

	"github.com/golang-jwt/jwt/v5"
)

// ErrInvalidToken is returned for any malformed, expired or wrongly-signed token.
var ErrInvalidToken = errors.New("invalid token")

// TokenKind distinguishes access from refresh tokens.
type TokenKind string

const (
	TokenAccess  TokenKind = "access"
	TokenRefresh TokenKind = "refresh"
)

// Claims is the JWT payload.
type Claims struct {
	AccountID int64     `json:"aid"`
	TenantID  int64     `json:"tid"`
	Role      string    `json:"role"`
	Kind      TokenKind `json:"knd"`
	jwt.RegisteredClaims
}

// JWTManager issues and validates HS256 tokens.
type JWTManager struct {
	secret     []byte
	issuer     string
	accessTTL  time.Duration
	refreshTTL time.Duration
}

// NewJWTManager builds a manager. secret must be non-empty (validated by config).
func NewJWTManager(secret, issuer string, accessTTL, refreshTTL time.Duration) *JWTManager {
	return &JWTManager{
		secret:     []byte(secret),
		issuer:     issuer,
		accessTTL:  accessTTL,
		refreshTTL: refreshTTL,
	}
}

// TokenPair is a freshly issued access+refresh pair plus the access token's jti and TTL.
type TokenPair struct {
	Access      string
	Refresh     string
	AccessJTI   string
	AccessTTLms int64 // access TTL in seconds
}

// Generate issues an access+refresh pair for a principal. `now` is supplied by the caller.
func (m *JWTManager) Generate(accountID, tenantID int64, role string, now time.Time) (TokenPair, error) {
	accessJTI, err := RandomToken(16)
	if err != nil {
		return TokenPair{}, err
	}
	refreshJTI, err := RandomToken(16)
	if err != nil {
		return TokenPair{}, err
	}

	access, err := m.sign(accountID, tenantID, role, TokenAccess, accessJTI, now, m.accessTTL)
	if err != nil {
		return TokenPair{}, err
	}
	refresh, err := m.sign(accountID, tenantID, role, TokenRefresh, refreshJTI, now, m.refreshTTL)
	if err != nil {
		return TokenPair{}, err
	}

	return TokenPair{
		Access:      access,
		Refresh:     refresh,
		AccessJTI:   accessJTI,
		AccessTTLms: int64(m.accessTTL.Seconds()),
	}, nil
}

// sign creates a signed token with the given claims. The jti is generated by the caller to link
func (m *JWTManager) sign(accountID, tenantID int64, role string, kind TokenKind, jti string, now time.Time, ttl time.Duration) (string, error) {
	// The jti is generated by the caller to link access and refresh tokens and support logout. The rest of the claims are self-explanatory. The standard RegisteredClaims are not strictly needed
	// but they add a layer of defence in depth and may be useful for future features (e.g. token
	// introspection endpoint, or a more complex token store that can query by expiry). The nbf
	// claim is set to the same value as iat to prevent "not valid yet" errors from small clock
	// skews between services.
	claims := Claims{
		AccountID: accountID,
		TenantID:  tenantID,
		Role:      role,
		Kind:      kind,
		RegisteredClaims: jwt.RegisteredClaims{
			ID:        jti,
			Issuer:    m.issuer,
			Subject:   fmt.Sprintf("%d", accountID),
			IssuedAt:  jwt.NewNumericDate(now),
			NotBefore: jwt.NewNumericDate(now),
			ExpiresAt: jwt.NewNumericDate(now.Add(ttl)),
		},
	}
	// The token is signed with the manager's secret and the HS256 algorithm. The parser will reject any token not signed with HS256, so we can be sure of the signing method when validating.
	// The token string is compact-serialized as per RFC7519.
	tok := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	// The SignedString method computes the HMAC signature and returns the complete token string. It can only fail if the signing method is misconfigured, so any error is wrapped in a fmt.Errorf and treated as unrecoverable.
	signed, err := tok.SignedString(m.secret)
	if err != nil {
		return "", fmt.Errorf("sign token: %w", err)
	}
	return signed, nil
}

// Parse validates a token and returns its claims. It pins the algorithm to HS256.
func (m *JWTManager) Parse(tokenString string) (*Claims, error) {
	var claims Claims
	_, err := jwt.ParseWithClaims(tokenString, &claims, func(t *jwt.Token) (any, error) {
		if _, ok := t.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, ErrInvalidToken
		}
		return m.secret, nil
	}, jwt.WithValidMethods([]string{"HS256"}), jwt.WithIssuer(m.issuer))
	if err != nil {
		return nil, ErrInvalidToken
	}
	return &claims, nil
}
